#!/usr/bin/env php
<?php
/**
 * Copyright (C) 2015 Marko Kercmar
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// PROJECT_ROOT
define('PROJECT_ROOT', realpath(__DIR__));

// composer
require PROJECT_ROOT . '/vendor/autoload.php';

// config
require PROJECT_ROOT . '/config.php';

// uses
use Aws\Ec2\Ec2Client;
use Aws\Ec2\Exception\Ec2Exception;

// init ec2 client
$ec2client = new Ec2Client([
    'region' => $config['Region'],
    'version' => 'latest',
    'debug' => false
    ]);

// logStreams
$logStreams = json_decode(
    file_get_contents(PROJECT_ROOT . '/data/logStreams.json'),
    true
    );

// coollect needed data
$instances = [];
$eni2ips = [];
$eni2instance = [];
$ip2cluster = [];
$ip2az = [];

foreach (array_keys($logStreams) as $eni) {
    $ips = [];
    $instanceId = false;

    // describe interface
    try {
        $res = $ec2client->describeNetworkInterfaces([
            'NetworkInterfaceIds' => [substr($eni, 0, 12)]
            ]);
    } catch (Ec2Exception $e) {
        // FIXME: Interface might be destroyed

        continue;
    }

    // require networkinterfaces
    if ($res->hasKey('NetworkInterfaces')) {
        foreach ($res->get('NetworkInterfaces') as $iface) {
            foreach ($iface['PrivateIpAddresses'] as $prvip) {
                if ($prvip['PrivateIpAddress']) {
                    $ips[] = $prvip['PrivateIpAddress'];
                }

                if (isset($prvip['Association']) && isset($prvip['Association']['PublicIp'])) {
                    $ips[] = $prvip['Association']['PublicIp'];
                }
            }

            if (isset($iface['Attachment']) && isset($iface['Attachment']['InstanceId'])) {
                $instanceId = $iface['Attachment']['InstanceId'];

                break;
            }
        }
    }

    // have instanceId?
    if (!$instanceId) continue;

    // store..
    $eni2ips[$eni] = $ips;
    $eni2instance[$eni] = $instanceId;

    // have instance or fetch?
    if (!isset($instances[$instanceId])) {
        try {
            $res = $ec2client->describeInstances([
                'InstanceIds' => array($instanceId)
                ]);
        } catch (Ec2Exception $e) {
            // FIXME: Instace might be destroyed

            continue;
        }

        // get interesting tags
        $tags = [];
        $az = 'unknown';

        // xx
        if ($res->hasKey('Reservations')) {
            $reservations = $res->get('Reservations');

            foreach ($reservations as $reservation) {
                foreach ($reservation['Instances'] as $instance) {
                    if (isset($instance['Tags'])) {
                        foreach ($instance['Tags'] as $tag) {
                            if ($tag['Key'] == 'Name') {
                                $tags['name'] = $tag['Value'];
                            } elseif ($tag['Key'] == 'Cluster') {
                                $tags['cluster'] = $tag['Value'];
                            }
                        }
                    }

                    if (isset($instance['Placement']) && isset($instance['Placement']['AvailabilityZone'])) {
                        $az = $instance['Placement']['AvailabilityZone'];
                    }
                }
            }
        }

        $instances[$instanceId] = [
            'tags' => $tags,
            'az' => $az
            ];

        $cluster = (isset($tags['cluster']) ? $tags['cluster'] : 'unknown');
    } else {
        $cluster = (isset($instances[$instanceId]['tags']['cluster']) ? $instances[$instanceId]['tags']['cluster'] : 'unknown');
    }

    // fill ip2cluster & ip2az
    foreach ($ips as $ip) {
        $ip2cluster[$ip] = $cluster;
        $ip2az[$ip] = $az;
    }
}

// anylze them
foreach (array_keys($logStreams) as $eni) {
    _log('analyzing ' . $eni);

    if (!isset($eni2ips[$eni])) continue;

    $ips = $eni2ips[$eni];

    // get events
    $fp = fopen(
        PROJECT_ROOT . '/data/' . $eni . '.log',
        'r'
        );

    $stats = [
        'first' => 0,
        'last' => 0,
        'in' => [
            'sum' => 0,
            'acc' => 0,
            'rej' => 0,
            'cluster' => [],
            'az' => [],
            'ip' => [],
            ],
        'out' => [
            'sum' => 0,
            'acc' => 0,
            'rej' => 0,
            'cluster' => [],
            'az' => [],
            'ip' => [],
            ],
        'total' => [
            'sum' => 0,
            'acc' => 0,
            'rej' => 0,
            'cluster' => [],
            'az' => [],
            'ip' => [],
            ],
        ];

    while (!feof($fp)) {
        $buffer = fgets($fp);

        if (!$buffer) break;

        $buffer = trim($buffer);

        if (!strlen($buffer)) break;

        $x = explode(' ', $buffer);

        if ($x[0] != 2) continue; // support flow log version 2 only

        list($version, $accountid, $interfaceid, $srcaddr, $dstaddr, $srcport, $dstport, $protocol, $packets, $bytes, $start, $end, $action, $logstatus) = $x;

        if ($stats['first'] == 0) $stats['first'] = $start;
        if ($start < $stats['first']) $stats['first'] = $start;

        if ($stats['last'] == 0) $stats['last'] = $end;
        if ($end > $stats['last']) $stats['last'] = $end;

        $a = false; $ip = false; $port = false;

        if (in_array($srcaddr, $ips)) {
            $a = 'out';
            $ip = $dstaddr;
            $port = $dstport;
        } else {
            $a = 'in';
            $ip = $srcaddr;
            $port = $srcport;
        }

        $cluster = 'unknown';
        if (isset($ip2cluster[$ip])) $cluster = $ip2cluster[$ip];

        $az = 'unknown';
        if (isset($ip2az[$ip])) $az = $ip2az[$ip];

        $b = false;

        if ($action == 'ACCEPT') $b = 'acc';
        else $b = 'rej';

        // in || out
        $stats[$a]['sum'] += $bytes;
        $stats[$a][$b] += $bytes;

        if (!isset($stats[$a]['cluster'][$cluster])) $stats[$a]['cluster'][$cluster] = 0;
        $stats[$a]['cluster'][$cluster] += $bytes;

        if (!isset($stats[$a]['az'][$az])) $stats[$a]['az'][$az] = 0;
        $stats[$a]['az'][$az] += $bytes;

        if (!isset($stats[$a]['ip'][$ip])) $stats[$a]['ip'][$ip] = 0;
        $stats[$a]['ip'][$ip] += $bytes;

        // total
        $stats['total']['sum'] += $bytes;
        $stats['total'][$b] += $bytes;

        if (!isset($stats['total']['cluster'][$cluster])) $stats['total']['cluster'][$cluster] = 0;
        $stats['total']['cluster'][$cluster] += $bytes;

        if (!isset($stats['total']['az'][$az])) $stats['total']['az'][$az] = 0;
        $stats['total']['az'][$az] += $bytes;

        if (!isset($stats['total']['ip'][$ip])) $stats['total']['ip'][$ip] = 0;
        $stats['total']['ip'][$ip] += $bytes;
    }

    file_put_contents(
        PROJECT_ROOT . '/data/' . $eni . '.stats.json',
        json_encode([
            'instanceId' => $eni2instance[$eni],
            'tags' => $instances[$eni2instance[$eni]]['tags'],
            'az' => $instances[$eni2instance[$eni]]['az'],
            'stats' => $stats
            ])
        );

    unset($stats);
}

// _log
function _log($msg)
{
    echo '[?] ' . $msg . "\n";
}
