#!/usr/bin/env php
<?php
// PROJECT_ROOT
define('PROJECT_ROOT', realpath(__DIR__));

// composer
require PROJECT_ROOT . '/vendor/autoload.php';

// config
require PROJECT_ROOT . '/config.php';

// uses
use Aws\Ec2\Ec2Client;
use Aws\Ec2\Exception\Ec2Exception;

// contains all data for generating HTML
$data = [];
//$data = json_decode(file_get_contents('x.json'), true);

// init ec2 client
$ec2client = new Ec2Client([
    'region' => $config['Region'],
    'version' => 'latest',
    'debug' => false
    ]);

// iterate over logStreams
$logStreams = json_decode(
    file_get_contents(PROJECT_ROOT . '/data/logStreams.json'),
    true
    );

foreach (array_keys($logStreams) as $eni) {
    if (!file_exists(PROJECT_ROOT . '/data/' . $eni . '.stats.json')) continue;

    $stats = json_decode(file_get_contents(PROJECT_ROOT . '/data/' . $eni . '.stats.json'), true);

    // describe interface
    try {
        $res = $ec2client->describeNetworkInterfaces([
            'NetworkInterfaceIds' => [substr($eni, 0, 12)]
            ]);
    } catch (Ec2Exception $e) {
        // FIXME: Interface might be destroyed

        continue;
    }

    // require attachment
    if ($res->hasKey('NetworkInterfaces')) {
        $instanceId = false;

        foreach ($res->get('NetworkInterfaces') as $iface) {
            if (isset($iface['Attachment']) && isset($iface['Attachment']['InstanceId'])) {
                $instanceId = $iface['Attachment']['InstanceId'];

                break;
            }
        }
    }

    if (!$instanceId) continue;

    // get instance data
    if (!isset($data[$instanceId])) {
        try {
            $res = $ec2client->describeInstances([
                'InstanceIds' => array($instanceId)
                ]);
        } catch (Ec2Exception $e) {
            // FIXME: Instace might be destroyed

            continue;
        }

        // get interesting tags
        $tags = [];

        // xx
        if ($res->hasKey('Reservations')) {
            $reservations = $res->get('Reservations');

            foreach ($reservations as $reservation) {
                foreach ($reservation['Instances'] as $instance) {
                    if (isset($instance['Tags'])) {
                        foreach ($instance['Tags'] as $tag) {
                            if ($tag['Key'] == 'Name') {
                                $tags['name'] = $tag['Value'];
                            } elseif ($tag['Key'] == 'Cluster') {
                                $tags['cluster'] = $tag['Value'];
                            }
                        }
                    }
                }
            }
        }
    }

    // store..
    if (!isset($data[$instanceId])) {
        $data[$instanceId] = [
            'instanceId' => $instanceId,
            'tags' => $tags,
            'stats' => $stats
            ];
    } else {
        // TODO: merge into existing entry, we currently only have one interface per instance, so not needed for us
    }
}

//file_put_contents('x.json', json_encode($data));

// sort via cluser & name
uasort(
    $data,
    function ($a, $b) {
        $s1 = (isset($a['tags']['cluster']) ? $a['tags']['cluser'] : 'z') . ' :: ';
        $s1 .= (isset($a['tags']['name']) ? $a['tags']['name'] : $a['instanceId']);

        $s2 = (isset($b['tags']['cluster']) ? $b['tags']['cluser'] : 'z') . ' :: ';
        $s2 .= (isset($b['tags']['name']) ? $b['tags']['name'] : $b['instanceId']);

        return strcmp($s1, $s2);
    });

$n = "\n"; $t = '  '; $tt = $t . $t; $ttt = $tt . $t; $tttt = $tt . $tt;

$o  = '';
$o .= '<!doctype html>' . $n;
$o .= '<html>' . $n;
$o .= '<head>' . $n;
$o .= $t . '<title>flowlog</title>' . $n;
$o .= '</head>' . $n;
$o .= '<body>' . $n;

foreach ($data as $instance) {
    $title  = (isset($instance['tags']['cluster']) ? $instance['tags']['cluser'] : 'unknown') . ' :: ';
    $title .= (isset($instance['tags']['name']) ? $instance['tags']['name'] : $instance['instanceId']);

    $o .= '<h1>' . $title . '</h1>' . $n;

    $o .= '<table border="1">' . $n;

    // head
    $o .= '<thead>' . $n;
    $o .= $t . '<tr>' . $n;
    $o .= $tt . '<th></th>' . $n;
    $o .= $tt . '<th>ACCEPT</th>' . $n;
    $o .= $tt . '<th>REJECT</th>' . $n;
    $o .= $tt . '<th>TOTAL</th>' . $n;
    $o .= $t . '</tr>' . $n;
    $o .= '</thead>' . $n;

    // body
    $o .= '<tbody>' . $n;

    // in
    $o .= $t . '<tr>' . $n;
    $o .= $tt . '<th>IN</th>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['in']['acc']['total']) . '</td>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['in']['rej']['total']) . '</td>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['in']['total']) . '</td>' . $n;
    $o .= $t . '</tr>' . $n;

    // out
    $o .= $t . '<tr>' . $n;
    $o .= $tt . '<th>OUT</th>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['out']['acc']['total']) . '</td>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['out']['rej']['total']) . '</td>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['out']['total']) . '</td>' . $n;
    $o .= $t . '</tr>' . $n;

    // total
    $o .= $t . '<tr>' . $n;
    $o .= $tt . '<th>TOTAL</th>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['total']['acc']['total']) . '</td>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['total']['rej']['total']) . '</td>' . $n;
    $o .= $tt . '<td>' . _format_bytes($instance['stats']['total']['total']) . '</td>' . $n;
    $o .= $t . '</tr>' . $n;

    $o .= '</tbody>' . $n;

    $o .= '</table>' . $n;
}

$o .= '</body>' . $n;
$o .= '</html>' . $n;

file_put_contents(
    PROJECT_ROOT . '/out/index.html',
    $o
    );

// _format_bytes($bytes, $precision);
function _format_bytes($size, $precision = 2)
{
    if ($size == 0) return 0;

    $base = log($size, 1024);
    $suffixes = array('', 'k', 'M', 'G', 'T');

    return round(pow(1024, $base - floor($base)), $precision) . $suffixes[floor($base)];
}
